### ISSUE TITLE
md-select events

### ISSUE THREAD

**Issue by heyitskippy** [vuematerial/vue-material#706]
Can't catch "open" and "close" events. And doc for them are wrong.

**Comment by Samuell1** [comment]
Example?

**Comment by vsamokhval** [comment]
Hi, I have the same issue.
[Here](https://github.com/marcosmoura/vue-material/issues/357) was added @opened and @closed events, but I found that in mdMenu.vue @open and @close events are emited.

**Comment by heyitskippy** [comment]
@Samuell1 https://codepen.io/heyitskippy/pen/QvdYKy

**Comment by vsamokhval** [comment]
As I can see, in [Develop](https://github.com/marcosmoura/vue-material/blob/develop/src/components/mdSelect/mdSelect.vue) branch this issue is fixed. I hope a new release will be soon.

**Comment by Samuell1** [comment]
@vsamokhval after 2. 5. we will see more activity :)

**Comment by pablohpsilva** [comment]
I'll close this issue since soon we'll have new features and this issue fixed, OK?

**Comment by dungla4** [comment]
Excuse me, is this issue solved or not? I check with vue-material 0.7.4 and still not working

**Comment by coeneivan** [comment]
Is this fixed? Can't get it to work...

**Comment by sijakret** [comment]
not working in 0.7.4..

**Comment by hm6293** [comment]
Hi,
Any update on this ?
I am using vue-material version 0.8.1 and still getting this issue.

**Comment by VdustR** [comment]
Hi, @hm6293 

The old vue material is deprecated and our focus is on the new 1.0.0 version.

Would you try `vue-material@beta` / `vue-material@1.0.0-beta-7`?

**Comment by hm6293** [comment]
@VdustR My app is currently build on old vue material and it will be a bit difficult to migrate the whole app to vue-material@beta because of one issue.
