### ISSUE TITLE
Docs website throws DNS error (vuematerial.io)

### ISSUE THREAD

**Issue by c941010623** [vuematerial/vue-material#868]
not work

**Comment by d3radicated** [comment]
It should be working now.

**Comment by JobJob** [comment]
It isn't

**Comment by JobJob** [comment]
Maybe I need to clear my dns cache?

**Comment by d3radicated** [comment]
@JobJob, yep. Just clear it and it will show up.

**Comment by JobJob** [comment]
Umm, it's still not up for me - it (`https://vuematerial.github.io`) redirects to `http://vuematerial.io/` but the address can't be resolved. Maybe the DNS change is still propagating?

**Comment by d3radicated** [comment]
Maybe, have you tried re-opening the browser?

**Comment by JobJob** [comment]
Yeah, anyway, I'll wait, looked up the DNS on a DNS Lookup  website and it was there. Thanks for your help, sorry about the noise.

**Comment by d3radicated** [comment]
@JobJob, no problem. We'll just wait for @c941010623 if it shows up for him to close this issue. :D

**Comment by tidus30691nexus5** [comment]
chang DNS: 
8.8.8.8
8.8.4.4
if not accept page

**Comment by JobJob** [comment]
It's up for me now btw, I think it was just a delay in the dns propagating.

**Comment by c941010623** [comment]
i find problem !!
when i use http://vuematerial.io/releases/v0.7.3/#/
it work ok
but
http://vuematerial.io/releases/v0.7.4/#/
not work

**Comment by Samuell1** [comment]
@c941010623 main release v0.7.4 is without `/releases/v0.7.4/#/` on http://vuematerial.io

**Comment by c941010623** [comment]
2016-last 15' macbook pro use safari
will get

404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

GitHub Status — @githubstatus
